- name: Assert directories exist
  file: path="{{ user.xdgconfig }}/systemd/user" state=directory

- include: misc.yml tags=misc
- include: tmux.yml tags=tmux
- include: tmuxinator.yml tags=tmuxinator
- include: vim.yml tags=vim
- include: zsh.yml tags=zsh
