- name: Assert directories exist
  file: path="{{ user.xdgconfig }}/systemd/user" state=directory

- include: misc.yml
- include: tmux.yml
- include: tmuxinator.yml
- include: vim.yml
- include: zsh.yml
