- name: Install packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
      - "fonts-powerline" # for vim status bar

- name: Assert directories exist
  file: path="{{ user.xdgconfig }}/systemd/user" state=directory

- include: misc.yml tags=misc
- include: tmux.yml tags=tmux
# - include: tmuxinator.yml tags=tmuxinator
- include: vim.yml tags=vim
- include: zsh.yml tags=zsh
