- name: Install packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
      - "tmux"

- name: Dotfiles
  template: src={{ item }} dest="{{ user.home }}/.{{ item }}"
  with_items:
      - "tmux.conf"
