#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export EDITOR=vim
export VISUAL=vim

zstyle ':prezto:module:git:status:ignore' submodules 'all'
zstyle ':prezto:module:git:info:context:subcontext' format 'string'

alias dt=dict
alias cp="cp"
alias tmuxa="tmux 2at -t"
alias tmuxn="tmux new -s"
alias tmux="tmux -2"

# use vim key bindings
bindkey -v
# xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
