#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export EDITOR=vim
export VISUAL=vim

zstyle ':prezto:module:git:status:ignore' submodules 'all'
zstyle ':prezto:module:git:info:context:subcontext' format 'string'

alias dt=dict
unsetopt NOCLOBBER
