- name: Install packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
      - "mutt"
      - "offlineimap"
      - "msmtp"
      - "inotify-tools"

- name: Copy dotfiles
  template: src={{ item }} dest="/home/{{ user.name }}/.{{ item }}" mode=0600
  with_items:
      - msmtprc
      - offlineimaprc
      - muttrc

- include: mailnotifydaemon.yml
