- name: Install packages
  become: True
  apt: pkg={{ item }} state=present
  with_items:
      - "neomutt"
      - "offlineimap"
      - "msmtp"
      - "inotify-tools"
      - "elinks"
      - "urlview"

- name: Copy dotfiles
  template: src={{ item }} dest="{{ user.home }}/.{{ item }}" mode=0600
  with_items:
      - mailcap

- include: mailcheck.yml
- include: mutt.yml tags=mutt
#- include: offlineimap.yml tags=offlineimap
