- name: Install packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
      - "mutt-patched"
      - "offlineimap"
      - "msmtp"
      - "inotify-tools"
      - "elinks"
      - "urlview"

- name: Copy dotfiles
  template: src={{ item }} dest="{{ user.home }}/.{{ item }}" mode=0600
  with_items:
      - msmtprc
      - offlineimaprc
      - muttrc
      - mailcap

- include: mailnotifydaemon.yml
- include: mutt.yml
- include: offlineimap.yml
