- name: Install packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
    - "apache2-mpm-itk"
    - "libapache2-mod-php5"

- name: Install Vhosts
  sudo: True
  template: src=apache_vhost dest="/etc/apache2/sites-available/{{ item.host }}.conf" mode=644
  with_items: hosts
  notify: restart-apache

- name: Enable sites
  sudo: True
  action: command a2ensite {{ item }}
  with_items:
    - "sulu.lo"
  notify: restart-apache

- name: Install hosts
  sudo: True
  template: src=hosts dest=/etc/hosts mode=0644
