- name: Install packages
  sudo: True
  apt: pkg={{ item }} state=present
  with_items:
      - "varnish"

- name: Install varnish config
  sudo: True
  template: src=varnish_sulu.vcl dest=/etc/varnish/default.vcl mode=0644
  notify: restart-varnish

